### ISSUE TITLE
Use gradio-i18n for multiple gr.TabItem

### ISSUE THREAD

**Issue by Eddycrack864** [hoveychen/gradio-i18n#1]
I want to use gradio-i18n to translate the entire gradio interface (I mean all the content of the gr.TabItems). I like this work because it allows manual language selection.

My plan is to create a gr.TabItem with a gr.Dropdown where the user can choose the language they want and the language will be changed to the selected one. Like my themes tab:
![image](https://github.com/user-attachments/assets/813ce05a-bfa7-46ad-8e9b-5aa4783034c8)

I've been trying with the examples described in the README but I only manage to change the language of the current gr.TabItem.

Can you provide me a small sample of how I should do this?

Maybe, if you have time this is my code where I want to integrate it:
https://github.com/Eddycrack864/UVR5-UI/blob/cc2c44b375fd517a16ecf798eec80e9fb68883dc/app.py#L422

**Comment by hoveychen** [comment]
Thanks for supporting. Would you try and see if this snippet meet your need?

```
import gradio as gr
from gradio_i18n import Translate
from gradio_i18n import gettext as _


def greet(name, gender, lang):
    return _("Greeting") + _("Hello {name} {gender} in {lang}").format(
        name=name, gender=gender, lang=lang
    )


with gr.Blocks() as demo:
    lang = gr.Radio(
        choices=[
            ("English", "en"),
            ("中文", "zh"),
            ("日本語", "ja"),
            ("한국인", "ko"),
            ("español", "es"),
            ("française", "fr"),
            ("Deutsch", "de"),
        ],
        label=_("Language"),
        render=False,
    )

    with Translate(
        "translation.yaml",
        lang,
        placeholder_langs=["en", "zh", "ja", "ko", "es", "fr", "de"],
    ):
        with gr.Tab(_("Demo")):
            name = gr.Textbox(label=_("Name"), placeholder=_("Input your name here."))
            gender = gr.Radio(choices=[_("Male"), _("Female"), _("Unknown")])
            output = gr.Textbox(label=_("Greeting"))
            submit_btn = gr.Button(value=_("Submit"))

            submit_btn.click(greet, inputs=[name, gender, lang], outputs=output)

        with gr.Tab(_("Setting")):
            lang.render()

demo.launch()

```

**Comment by Eddycrack864** [comment]
It worked! Tysm for the sample, it now works just like I wanted.

Keep up this amazing work!
